version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "monthly"
      day: "monday"
      time: "07:38"
      timezone: "UTC"

updates:
  - package-ecosystem: "nix"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "dependencies"
    commit-message:
      prefix: "deps:"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "dependencies"
    commit-message:
      prefix: "deps:"
